apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: game-config
  namespace: default
  resourceVersion: "516"
  uid: b4952dc3-d670-11e5-8cd0-68f728db1985
{{ include "test-helm-dep.test" . | indent 2}}
data:
  game.properties: |-
{{- $file := print "files/server-" .Values.ENV ".env"}}
{{ .Files.Get $file | indent 4 }}